# File: app/utils/tipo_beneficio.py
TIPO_BENEFICIO_MAP = {
    "01": "Pensão por morte do trabalhador rural",
    "02": "Pensão por morte por acidente do trabalho do trabalhador rural",
    "03": "Pensão por morte do empregador rural",
    "04": "Aposentadoria por invalidez do trabalhador rural",
    "05": "Aposentadoria por invalidez por acidente do trabalho do trabalhador rural",
    "06": "Aposentadoria por invalidez do empregador rural",
    "07": "Aposentadoria por idade do trabalhador rural",
    "08": "Aposentadoria por idade do empregador rural",
    "10": "Auxílio-doença por acidente do trabalho do trabalhador rural",
    "11": "Renda mensal vitalícia por invalidez do trabalhador rural (Lei nº 6.179/74)",
    "12": "Renda mensal vitalícia por idade do trabalhador rural (Lei nº 6.179/74)",
    "13": "Auxílio-doença do trabalhador rural",
    "15": "Auxílio-reclusão do trabalhador rural",
    "21": "Pensão por morte previdenciária",
    "22": "Pensão por morte estatutária",
    "23": "Aposentadoria por invalidez previdenciária",
    "24": "Aposentadoria por idade previdenciária",
    "25": "Auxílio-doença previdenciário",
    "26": "Auxílio-reclusão previdenciário",
    "27": "Renda mensal vitalícia por invalidez previdenciária",
    "28": "Renda mensal vitalícia por idade previdenciária",
    "29": "Pensão por morte de servidor público",
    "30": "Aposentadoria por invalidez de servidor público",
    "31": "Aposentadoria por idade de servidor público",
    "32": "Auxílio-doença de servidor público",
    "33": "Auxílio-reclusão de servidor público",
    "34": "Renda mensal vitalícia por invalidez de servidor público",
    "35": "Renda mensal vitalícia por idade de servidor público",
    "40": "Pensão por morte de dependente de servidor público",
    "41": "Aposentadoria por invalidez de dependente de servidor público",
    "42": "Aposentadoria por idade de dependente de servidor público",
    "43": "Auxílio-doença de dependente de servidor público",
    "44": "Auxílio-reclusão de dependente de servidor público",
    "45": "Renda mensal vitalícia por invalidez de dependente de servidor público",
    "46": "Renda mensal vitalícia por idade de dependente de servidor público",
    "50": "Pensão por morte de dependente do trabalhador",
    "51": "Aposentadoria por invalidez de dependente do trabalhador",
    "52": "Aposentadoria por idade de dependente do trabalhador",
    "53": "Auxílio-doença de dependente do trabalhador",
    "54": "Auxílio-reclusão de dependente do trabalhador",
    "55": "Renda mensal vitalícia por invalidez de dependente do trabalhador",
    "56": "Renda mensal vitalícia por idade de dependente do trabalhador",
    "57": "Pensão por morte de dependente do trabalhador rural",
    "58": "Aposentadoria por invalidez de dependente do trabalhador rural",
    "59": "Aposentadoria por idade de dependente do trabalhador rural",
    "60": "Auxílio-doença de dependente do trabalhador rural",
    "61": "Auxílio-reclusão de dependente do trabalhador rural",
    "62": "Renda mensal vitalícia por invalidez de dependente do trabalhador rural",
    "63": "Renda mensal vitalícia por idade de dependente do trabalhador rural",
    "64": "Pensão por morte de dependente de servidor público rural",
    "65": "Aposentadoria por invalidez de dependente de servidor público rural",
    "66": "Aposentadoria por idade de dependente de servidor público rural",
    "67": "Auxílio-doença de dependente de servidor público rural",
    "68": "Auxílio-reclusão de dependente de servidor público rural",
    "69": "Renda mensal vitalícia por invalidez de dependente de servidor público rural",
    "70": "Renda mensal vitalícia por idade de dependente de servidor público rural",
    "71": "Pensão por morte do trabalhador autônomo",
    "72": "Aposentadoria por invalidez do trabalhador autônomo",
    "73": "Aposentadoria por idade do trabalhador autônomo",
    "74": "Auxílio-doença do trabalhador autônomo",
    "75": "Auxílio-reclusão do trabalhador autônomo",
    "76": "Renda mensal vitalícia por invalidez do trabalhador autônomo",
    "77": "Renda mensal vitalícia por idade do trabalhador autônomo",
    "78": "Pensão por morte do dependente do trabalhador autônomo",
    "79": "Aposentadoria por invalidez do dependente do trabalhador autônomo",
    "80": "Aposentadoria por idade do dependente do trabalhador autônomo",
    "81": "Auxílio-doença do dependente do trabalhador autônomo",
    "82": "Auxílio-reclusão do dependente do trabalhador autônomo",
    "83": "Renda mensal vitalícia por invalidez do dependente do trabalhador autônomo",
    "84": "Renda mensal vitalícia por idade do dependente do trabalhador autônomo",
    "85": "Pensão por morte do trabalhador empregado",
    "86": "Aposentadoria por invalidez do trabalhador empregado",
    "87": "Aposentadoria por idade do trabalhador empregado",
    "88": "Auxílio-doença do trabalhador empregado",
    "89": "Auxílio-reclusão do trabalhador empregado",
    "90": "Renda mensal vitalícia por invalidez do trabalhador empregado",
    "91": "Renda mensal vitalícia por idade do trabalhador empregado",
    "92": "Aposentadoria por invalidez por acidente do trabalho",
    "93": "Pensão por morte por acidente do trabalho",
    "94": "Auxílio-acidente por acidente do trabalho",
    "95": "Auxílio-suplementar por acidente do trabalho",
    "96": "Pensão especial às pessoas atingidas pela hanseníase (Lei nº 11.520/2007)"
}
